### PR TITLE
Migrate to liblouis 3.20

### PR DESCRIPTION
**Pull request by egli**
Basically replace all `uplow` opcodes with `lowercase` and `base`

### CODE REVIEW

**Comment by bertfrees** [comment]
It seems rules in nemeth.ctb like `always ^< 126` don't work when there are capitals. I don't know why.

**Comment by egli** [comment]
OK, thanks @bertfrees 

I guess I'll just mark the tests as `XFAIL` then and leave this bug for someone else to find.

**Comment by bertfrees** [comment]
That makes little sense I think. XFAIL is not meant to ignore bugs.

**Comment by egli** [comment]
I understand that. But let's be honest: we are not maintaining liblouisutdml, we are just providing live support. I sort of made it work with the newest liblouis answering to issue #75 that @sthibaul reported.

What action would you suggest? That I go ahead and try to fix the problem with `always ^< 126`?

Which reminds me, I have an update for `viewxml.ctb` that I should push.

**Comment by bertfrees** [comment]
This happens because of the `checkEmphasisChange()` function which is called when checking whether an `always` or `word` rule matches and which should return `1` when there is a change of emphasis or capitalisation somewhere inside the contraction. Apparently some change between Liblouis 3.17 and 3.20 makes this function return `1` where it didn't before.

**Comment by bertfrees** [comment]
The regression was caused by commit beec4b105f7c44a972544785e710b3467b1d5eff: here I moved some code from `resolveEmphasisAllSymbols()` to `insertEmphasisSymbol()` but didn't think about `checkEmphasisChange()`.

**Comment by egli** [comment]
Hm, interesting, so you found a bug in liblouis by persisting

**Comment by egli** [comment]
> Don't we also need to fix `lbu_files/viewxml.ctb` which still contains `uplow`?

Yes probably. It doesn't seem to bother the test suite and I don't know what it is for, but yes this probably should be fixed.

**Comment by sthibaul** [comment]
Also, e.g. `pagenum.cti` is made to use only `lowercase`, but `latinLetterDef8Dots.uti` is made to use both `lowercase` and `uppercase`. Do we need to use the latter or the former approach?

**Comment by egli** [comment]
I basically just made the test work again. The pagenum stuff only seems to exercise lowercase chars. And the `latinLetterDef8Dots.uti` seems to be part of some Java binding test suite. I don't think that this is even run during the normal test suite. AFAIR I just copied the table from the liblouis sources.

So as far as I'm concerned the changes should be OK. They both are just made for the tests. So to answer your question I think it's OK to use different approaches for `pagenum.cti` and `latinLetterDef8Dots.uti`

**Comment by sthibaul** [comment]
Ok, so this should be fine for viewxml.ctb:
[patch.txt](https://github.com/liblouis/liblouisutdml/files/8041948/patch.txt)

**Comment by egli** [comment]
So as far as I'm concerned this patch could go in. Sure it masks the liblouis regression (liblouis/liblouis#1152) but utdml test suite now passes and we can create a release that will work with liblouis 3.20. Once this is fixed in liblouis there will be unexpected passes but that is OK.

So @bertfrees what do you say? Ready to merge?

**Comment by egli** [comment]
If we do not use XFAILS then there will be no utdml release that works with liblouis 3.20 as far as I know. The original complaint was that the test suite was failing. This was mostly due to the `uplow` incompatibility, but also because of the regression. The regression will be fixed by applying a patch to liblouis or waiting for liblouis 3.21. But thb I feel a bit weird releasing a utdml release that only works with a patched liblouis. 

OTOH I guess it is also weird to release utdml with silent regressions. But hopefully this is a temporary situation.

**Pull request merged**
