### PR TITLE
Without internal.h

### PR DESCRIPTION
**Pull request by egli**
Try to get rid of the dependency on `liblouis/internal.h`

The compilation fails due to unknown type name `TranslationTableRule` and `TranslationTableOffset`. I don't know how to solve that atm.

### CODE REVIEW

**Comment by egli** [comment]
This should be adapted to the changes in liblouis/liblouis#754 where part of the internal api has been cleaned up and moved to the public API

**Comment by egli** [comment]
As far as I can see it crashes because `readconfig.c` is using the (no longer exported) function `_lou_getLastTableList`. This function seems to cache the name of the last used table. It is defined in liblouis but only used in utdml. Any idea @bertfrees ?

**Comment by bertfrees** [comment]
Yes. I would change the findTable fucntion so that it doesn't need to use _lou_getLastTableList anymore. (And presumably we can then also remove it from internal.h?) Commit cdac707 is also related.

**Comment by bertfrees** [comment]
> The function seems to just grab the name of the last compiled table, which in this case should be the input of the last call to `lou_getTable`.

OK, apparently this is true. Weird.

I would rather see the whole function be replaced by lou_getTable, and lou_registerTableResolver be used to add the Liblouisutdml specific file resolving stuff. But then again I don't really care.

The only thing that concerns me is that this change basically changes nothing but yet it seems to do exactly what I did in cdac707, so why did I even have to do it?

**Comment by egli** [comment]
> this change basically changes nothing but yet it seems to do exactly what I did in cdac707, so why did I even have to do it?

I'm not sure the two are related. Afaik my change uses the string that was passed to `lou_getTable` instead of invoking the `_lou_getLastTableList` function.

Your change OTOH mucks around with the input string of `lou_getTable` if the table wasn't found by `find_file` which doesn't seem to use the code that I changed.

**Comment by bertfrees** [comment]
OK, now I remember. It's worse than I thought. I assumed `change_table` would use `findTable` but that's not the case. And `find_file` has nothing in common with `findTable`. That's some bad written code.

**Pull request merged**
