### PR TITLE
Update MathML processing code and tests so that it works with file2brl

### PR DESCRIPTION
**Pull request by NSoiffer**

### CODE REVIEW

**Comment by bertfrees** [comment]
Hi @NSoiffer,

There is something I don't quite get. The Github Actions system tells us that the test suite worked fine, but your commit https://github.com/liblouis/liblouisutdml/pull/87/commits/451c74cf9d7c788de58e5cd572a9de9b8e3b7dc7 made it fail. So I don't see how this is an improvement. Are you saying that on your system the test suite didn't work before and now it works?

Your last commit which adds the many new tests is of course great.

I'm thinking about how we can move these tests to Liblouis (like we did for UEB in https://github.com/liblouis/liblouis/pull/1310), so that we can move nemeth.ctb back to Liblouis also (https://github.com/liblouis/liblouis/issues/815). The problem is that I can not simply use the approach of https://github.com/liblouis/liblouis/pull/1310 because nemeth.ctb is designed for use with nemeth.sem, not mathml.xsl. I have two options:
- Write a new XSLT that replaces nemeth.sem (and add a second translation pass with nemeth_edit.ctb).
- Replace nemeth.ctb with the table from BrailleBlaster.

**Comment by hammera** [comment]
Hi,

In tests/mathml_nemeth/liblouisutdml.ini I need do following modification to works the test system:
Need change the ../lbu_files path with ../../lbu_files to works the test system again.
Note:
Because previous the edit table used en-us-brf.dis file 31 nemeth tests failed, because the expected.txt contains usa braille output, not unicode Braille output.

Attila

**Comment by hammera** [comment]
@NSoiffer, I forgot a thing:
Matrix line not need comment out with lbu_files/nemeth.sem file. In tests/mathml_nemeth/styles.cfg enough put following modification to liblouis not drop error message the undefined matrix style related when file2brl examine your tests:
```
style matrix
	format alignColumnsLeft
```

Bert, possible happen checking error because not good the tests/mathml_nemeth/liblouis.ini the table path variables, and mismatch .github/workflow/sanitizer.yml file the Liblouis version?
The .github/workflow/main.yml file we migrated with Liblouis 3.26.0 version, but forgot doing this migration the .github/workflow/sanitizer.yml file.
Default the sanitizer.yml file contains Liblouis 3.21 version.

When I working @norbertmarkus the #96 related pull request in monday, we experienced similar check results with first time.

Hope this help,

Attila

**Comment by egli** [comment]
Has been superseded by #98

**Pull request closed without merging**
